name: Generate 3D Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AkshitTiwarii
          outputs: |
            output/profile-3d-contrib/profile-night-rainbow.svg
