name: Build 3D Skyline
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AkshitTiwarii
          outputs: |
            output/profile-3d-contrib/profile-night.svg
